import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Loader2, ShieldCheck, Eye, EyeOff } from "lucide-react";
import { useLanguage } from "@/hooks/useLanguage";

// NOTE: supabase client file is autogenerated and doesn't export these constants.
// We keep these publishable values here only to allow robust error parsing even
// when the function returns non-2xx (Supabase client won't expose the JSON body).
const SUPABASE_URL = "https://jboartixfhvifdecdufq.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impib2FydGl4Zmh2aWZkZWNkdWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTc4OTgsImV4cCI6MjA3MTI3Mzg5OH0.cCa4TBR8TX9rOHy4AaKj2QRzHZIg6vc06eEkbUiHzo4";

interface PasswordResetDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  email: string;
  onSuccess: () => void;
}

export const PasswordResetDialog = ({ 
  open, 
  onOpenChange, 
  email,
  onSuccess 
}: PasswordResetDialogProps) => {
  const [code, setCode] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const { t } = useLanguage();

  const handleVerifyCode = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (code.length !== 5) {
      toast({
        title: t("password.reset.invalid_code"),
        description: t("password.reset.code_must_be_5"),
        variant: "destructive",
      });
      return;
    }

    if (newPassword.length < 6) {
      toast({
        title: t("password.reset.short_password"),
        description: t("password.reset.min_6_chars"),
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);

    try {
      // IMPORTANTE:
      // O supabase.functions.invoke lança "Runtime error" (na UI do Lovable) quando a Edge Function
      // responde com status non-2xx (ex.: 400/401), mesmo que o body tenha uma mensagem amigável.
      // Para garantir que SEMPRE mostramos a mensagem correta (e evitar a tela/alerta de runtime),
      // chamamos via fetch e interpretamos o JSON manualmente.

      const res = await fetch(`${SUPABASE_URL}/functions/v1/verify-password-reset-code`, {
        method: "POST",
        headers: {
          apikey: SUPABASE_ANON_KEY,
          authorization: `Bearer ${SUPABASE_ANON_KEY}`,
          "content-type": "application/json",
        },
        body: JSON.stringify({ email, code, newPassword }),
      });

      const json = await res.json().catch(() => null);
      const data = json as { success?: boolean; error?: string; message?: string } | null;

      console.log("[PasswordReset] HTTP:", { status: res.status, data });

      // Sucesso
      if (data?.success) {
        toast({
          title: t("password.reset.success"),
          description: t("password.reset.success_desc"),
        });
        
        onOpenChange(false);
        onSuccess();
        return;
      }

      // Erro
      const errorMessage = data?.error || "";

      // Mapear erros específicos para mensagens amigáveis
      let friendlyMessage = t("password.reset.generic_error");

      // Se a API já retornou uma mensagem em PT-BR, priorizamos mostrar exatamente ela
      // (você pediu: "Código inválido ou já utilizado").
      if (errorMessage === "Código inválido ou já utilizado") {
        friendlyMessage = errorMessage;
      } else if (
        errorMessage ===
        "Senha muito fraca. Use uma senha mais forte com letras, números e símbolos."
      ) {
        friendlyMessage = errorMessage;
      }
      
      // Código inválido ou já utilizado
      else if (errorMessage.toLowerCase().includes("inválido") || 
          errorMessage.toLowerCase().includes("invalid") ||
          errorMessage.toLowerCase().includes("já utilizado") ||
          errorMessage.toLowerCase().includes("already used")) {
        friendlyMessage = "Código inválido ou já utilizado";
      } 
      // Código expirado
      else if (errorMessage.toLowerCase().includes("expirado") || 
               errorMessage.toLowerCase().includes("expired")) {
        friendlyMessage = t("password.reset.expired_code_msg");
      } 
      // Senha fraca
      else if (errorMessage.toLowerCase().includes("fraca") || 
               errorMessage.toLowerCase().includes("weak") || 
               errorMessage.toLowerCase().includes("easy to guess") ||
               errorMessage.toLowerCase().includes("password") ||
               errorMessage.toLowerCase().includes("senha")) {
        friendlyMessage = t("password.reset.weak_password_msg");
      }
      
      toast({
        title: t("password.reset.error"),
        description: friendlyMessage,
        variant: "destructive",
      });
    } catch (error: any) {
      console.error("[PasswordReset] Catch error:", error);
      toast({
        title: t("password.reset.error"),
        description: t("password.reset.try_again"),
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/\D/g, "").slice(0, 5);
    setCode(value);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader className="text-center pb-4">
          <div className="w-12 h-12 bg-gradient-neon rounded-xl flex items-center justify-center mx-auto mb-3">
            <ShieldCheck className="w-6 h-6 text-white" />
          </div>
          <DialogTitle className="text-xl font-bold">{t("password.reset.title")}</DialogTitle>
          <DialogDescription className="text-center">
            {t("password.reset.sent")} <strong>{email}</strong>
            <br />
            <span className="text-xs text-muted-foreground">
              {t("password.reset.expires")}
            </span>
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleVerifyCode} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="code" className="text-center block">
              {t("password.reset.code_label")}
            </Label>
            <Input
              id="code"
              type="text"
              inputMode="numeric"
              pattern="[0-9]*"
              value={code}
              onChange={handleCodeChange}
              placeholder="00000"
              className="text-center text-2xl font-bold tracking-widest"
              maxLength={5}
              required
              autoFocus
            />
            <p className="text-xs text-muted-foreground text-center">
              {t("password.reset.code_hint")}
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="newPassword">{t("password.reset.new_password")}</Label>
            <div className="relative">
              <Input
                id="newPassword"
                type={showPassword ? "text" : "password"}
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                placeholder={t("password.reset.new_password_placeholder")}
                className="pr-10"
                minLength={6}
                required
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              >
                {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              </button>
            </div>
            <p className="text-xs text-muted-foreground">
              {t("password.reset.min_chars")}
            </p>
          </div>

          <Button 
            type="submit" 
            disabled={isLoading || code.length !== 5 || newPassword.length < 6} 
            className="w-full"
          >
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                {t("password.reset.verifying")}
              </>
            ) : (
              <>
                <ShieldCheck className="w-4 h-4 mr-2" />
                {t("password.reset.button")}
              </>
            )}
          </Button>

          <p className="text-xs text-center text-muted-foreground">
            {t("password.reset.no_code")}
          </p>
        </form>
      </DialogContent>
    </Dialog>
  );
};
