// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjdkyqyxxvvduesjlwvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZGt5cXl4eHZ2ZHVlc2psd3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTU1NDMsImV4cCI6MjA2OTQ3MTU0M30.fBhpHQB0IzDySTDkz0gqU2Goi4Kam4xDdSVfoiBIo-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});